# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

In [45]:
# Import your libraries:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# Challenge 1 - Explore the Scikit-Learn Datasets

Before starting to work on our own datasets, let's first explore the datasets that are included in this Python library. These datasets have been cleaned and formatted for use in ML algorithms.

First, we will load the diabetes dataset. Do this in the cell below by importing the datasets and then loading the dataset  to the `diabetes` variable using the `load_diabetes()` function.

In [18]:
# Your code here:
from sklearn import datasets
diabetes = datasets.load_diabetes
diabetes = diabetes()
diabetes

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990842, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06832974, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286377, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04687948,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452837, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00421986,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

Let's explore this variable by looking at the different attributes. Do this by looking at the `keys()` of this variable.

In [20]:
# Your code here:
diabetes.keys()

dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename'])

The next step is to read the description of the dataset. Print the description in the cell below using the `DESCR` attribute of the `diabetes` variable

In [21]:
# Your code here:
diabetes.DESCR

'.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n  :Number of Instances: 442\n\n  :Number of Attributes: First 10 columns are numeric predictive values\n\n  :Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n  :Attribute Information:\n      - age     age in years\n      - sex\n      - bmi     body mass index\n      - bp      average blood pressure\n      - s1      tc, T-Cells (a type of white blood cells)\n      - s2      ldl, low-density lipoproteins\n      - s3      hdl, high-density lipoproteins\n      - s4      tch, thyroid stimulating hormone\n      - s5      ltg, lamotrigine\n      - s6      glu, blood sugar level\n\nNo

What are the variables in this dataset according to the description? List them in the markdown cell below

#### Enter your answer here:




1. age, age in years
2. sex
3. bmi, body mass
4. bp, average blood pressure
5. s1, tc, T-Cells (a type of white blood cells)
6. s2, ldl, low-density lipoproteins
7. s3, hdl, high-density lipoproteins
8. s4, tch, thyroid stimulating hormone
9. s5, ltg, lamotrigine 
10. s6, glu, blood sugar level

Now explore the data. Scikit-learn typically takes in 2D numpy arrays as input (though pandas dataframes are also accepted). In the cell below find the shape of the numpy array contained in the data portion of the diabetes variable.

In [37]:
df = pd.DataFrame(diabetes.data)
df.head()

0         1         2         3         4         5         6  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

          7         8         9  
0 -0.002592  0.019908 -0.017646  
1 -0.039493 -0.068330 -0.092204  
2 -0.002592  0.002864 -0.025930  
3  0.034309  0.022692 -0.009362  
4 -0.002592 -0.031991 -0.046641

In [38]:
#cada columna representa los nomnbres de las variables arriba listadas.

In [39]:
# Your code here:
diabetes.data.shape
#Tiene 442 filas y 10 columnas.

(442, 10)

# Challenge 2 - Perform Supervised Learning on the Dataset

#### The data has already been split to predictor and response variables. The response variable is in the `target` portion of the variable. 

Given this information, let's apply what we have previously learned about linear regression and apply the algorithm to the diabetes dataset. In the cell below, import the linear regression class from sklearn. 

In [40]:
# Your code here:
diabetes.target

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [50]:
from sklearn.linear_model import LinearRegression

Initialize the model in the variable `diabetes_model`

In [59]:
# Your code here:
diabetes_model = LinearRegression(fit_intercept=True)

In [60]:
diabetes_model.fit(diabetes.data, diabetes.target)

LinearRegression()

In the cell below, fit the model and print the intercept and coefficients of the model. 

In [64]:
# Your code here:
# intercept
print(diabetes_model.intercept_)

152.1334841628965


In [66]:
#coefficients
print(diabetes_model.coef_)

[ -10.01219782 -239.81908937  519.83978679  324.39042769 -792.18416163
  476.74583782  101.04457032  177.06417623  751.27932109   67.62538639]


# Bonus Challenge 1 - Conduct a Hypothesis Test on the Model

Once we have generated a linear model, we can test each coefficient using a t-test to see whether the confidence interval for the variable contains zero. We can also perform an overall F test to check whether at least one coefficient is significantly different from zero. 

Refer to the resource in this [link](https://onlinecourses.science.psu.edu/stat501/node/297/) for more details and perform the t-tests for the model above. Additionally, interpret the results and list coefficients are significantly different from zero.


Hint: use the statsmodels package.

Your result should look similar to this:

![ols](../ols-results.png)

In [189]:
# Your code here:
import statsmodels.formula.api as smf

In [199]:
res = smf.ols("target ~ data", data = diabetes).fit()
res

In [200]:
res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 target   R-squared:                       0.518
Model:                            OLS   Adj. R-squared:                  0.507
Method:                 Least Squares   F-statistic:                     46.27
Date:                Wed, 24 Feb 2021   Prob (F-statistic):           3.83e-62
Time:                        00:50:18   Log-Likelihood:                -2386.0
No. Observations:                 442   AIC:                             4794.
Df Residuals:                     431   BIC:                             4839.
Df Model:                          10                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    152.1335      2.576     59.061      0.000     147.071     157.196
data[0]      -10.0122     59.749     -0.168      0.867    -127.448     107.424
data[1]     -239.8191     61.222     -3.917      0.000    -360.151    -119.488
data[2]      519.8398     66.534      7.813      0.000     389.069     650.610
data[3]      324.3904     65.422      4.958      0.000     195.805     452.976
data[4]     -792.1842    416.684     -1.901      0.058   -1611.169      26.801
data[5]      476.7458    339.035      1.406      0.160    -189.621    1143.113
data[6]      101.0446    212.533      0.475      0.635    -316.685     518.774
data[7]      177.0642    161.476      1.097      0.273    -140.313     494.442
data[8]      751.2793    171.902      4.370      0.000     413.409    1089.150
data[9]       67.6254     65.984      1.025      0.306     -62.065     197.316
==============================================================================
Omnibus:                        1.506   Durbin-Watson:                   2.029
Prob(Omnibus):                  0.471   Jarque-Bera (JB):                1.404
Skew:                           0.017   Prob(JB):                        0.496
Kurtosis:                       2.726   Cond. No.                         227.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# Challenge 2 - Peform Supervised Learning on a Pandas Dataframe

Now that we have looked at data that has been formatted for scikit-learn, let's look at data that we will need to format ourselves.

In the next cell, load the `auto-mpg.csv` file included in this folder and assign it to a variable called `auto`.

In [68]:
# Your code here:
auto = pd.read_csv('../auto-mpg.csv')

Look at the first 5 rows using the `head()` function:

In [69]:
# Your code here:
auto.head()

mpg  cylinders  displacement  horse_power  weight  acceleration  \
0  18.0          8         307.0        130.0    3504          12.0   
1  15.0          8         350.0        165.0    3693          11.5   
2  18.0          8         318.0        150.0    3436          11.0   
3  16.0          8         304.0        150.0    3433          12.0   
4  17.0          8         302.0        140.0    3449          10.5   

   model_year                       car_name  
0          70  \t"chevrolet chevelle malibu"  
1          70          \t"buick skylark 320"  
2          70         \t"plymouth satellite"  
3          70              \t"amc rebel sst"  
4          70                \t"ford torino"

In [99]:
auto.shape

(398, 8)

Evaluate the data to ensure that all numeric columns are correctly detected as such by pandas. If a column is misclassified as object, coerce it to numeric.

In [80]:
# Your code here:
auto.dtypes

mpg             float64
cylinders         int64
displacement    float64
horse_power     float64
weight            int64
acceleration    float64
model_year        int64
car_name         object
dtype: object

What is the newest model year and the oldest model year?

In [82]:
# Your code here:
auto.model_year.unique()

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82])

In [93]:
auto.model_year.max()

82

In [94]:
auto.model_year.min()

70

In [47]:
year_model = list(auto.groupby('model_year')['car_name'].max())
year_model

['\t"volkswagen 1131 deluxe sedan"',
 '\t"volkswagen model 111"',
 '\t"volvo 145e (sw)"',
 '\t"volvo 144ea"',
 '\t"volkswagen dasher"',
 '\t"volvo 244dl"',
 '\t"vw rabbit"',
 '\t"volkswagen rabbit custom"',
 '\t"volvo 264gl"',
 '\t"vw rabbit custom"',
 '\t"vw rabbit"',
 '\t"volvo diesel"',
 '\t"vw pickup"']

In [42]:
year_model[0]

'\t"volkswagen 1131 deluxe sedan"'

In [43]:
year_model[-1]

'\t"vw pickup"'

Check the dataset for missing values and remove all rows containing at least one missing value.

In [97]:
# Your code here:
auto.isnull().sum()

mpg             0
cylinders       0
displacement    0
horse_power     6
weight          0
acceleration    0
model_year      0
car_name        0
dtype: int64

In [187]:
auto = auto.dropna()
auto.head()

mpg  cylinders  displacement  horse_power  weight  acceleration  \
0  18.0          8         307.0        130.0    3504          12.0   
1  15.0          8         350.0        165.0    3693          11.5   
2  18.0          8         318.0        150.0    3436          11.0   
3  16.0          8         304.0        150.0    3433          12.0   
4  17.0          8         302.0        140.0    3449          10.5   

   model_year                       car_name  
0          70  \t"chevrolet chevelle malibu"  
1          70          \t"buick skylark 320"  
2          70         \t"plymouth satellite"  
3          70              \t"amc rebel sst"  
4          70                \t"ford torino"

In [188]:
auto.shape

(392, 8)

In [93]:
#Se han borrado las 6 filas con valores nulos de horse_power

Find the frequency table for the `cylinders` column using the `value_counts()` function. How many possible values of cylinders are there?

In [94]:
# Your code here:
auto.cylinders.value_counts()

4    199
8    103
6     83
3      4
5      3
Name: cylinders, dtype: int64

In [95]:
#Pueden tener; 4, 8, 6, 3 o 5 cylinders.

We would like to generate a linear regression model that will predict mpg. To do this, first drop the `car_name` column since it does not contain any quantitative data. Next separate the dataframe to predictor and response variables. Separate those into test and training data with 80% of the data in the training set and the remainder in the test set. 

Assign the predictor and response training data to `X_train` and `y_train` respectively. Similarly, assign the predictor and response test data to `X_test` and `y_test`.

In [101]:
auto.drop(columns=["car_name"])[:10]

mpg  cylinders  displacement  horse_power  weight  acceleration  \
0  18.0          8         307.0        130.0    3504          12.0   
1  15.0          8         350.0        165.0    3693          11.5   
2  18.0          8         318.0        150.0    3436          11.0   
3  16.0          8         304.0        150.0    3433          12.0   
4  17.0          8         302.0        140.0    3449          10.5   
5  15.0          8         429.0        198.0    4341          10.0   
6  14.0          8         454.0        220.0    4354           9.0   
7  14.0          8         440.0        215.0    4312           8.5   
8  14.0          8         455.0        225.0    4425          10.0   
9  15.0          8         390.0        190.0    3850           8.5   

   model_year  
0          70  
1          70  
2          70  
3          70  
4          70  
5          70  
6          70  
7          70  
8          70  
9          70

In [102]:
# Import the necessary function
from sklearn.model_selection import train_test_split

In [108]:
# Your code here:
data_x = auto[["cylinders", "displacement", "horse_power", "weight", "model_year"]]
data_y = auto["mpg"]

X_train, x_test, Y_train, y_test = train_test_split(data_x,data_y, test_size=0.2, random_state=None)

Now we will the dataset that we processed and peform linear regression on this data to predict the mpg for each vehicle. Initialize the model in the cell below.

In [109]:
# Your code here:
alm = LinearRegression()
alm

LinearRegression()

Next, fit the model in the cell below.

In [110]:
# Your code here:
amodel = lma.fit(X_train, Y_train)
amodel

LinearRegression()

In [112]:
amodel.intercept_

-13.438671043284064

In [113]:
amodel.coef_

array([-0.27511831,  0.00512443, -0.00616939, -0.00679237,  0.76537948])

# Challenge 3 - Evaluate the Model

the r squared score of a model tells us how much variation is explained by the model. In a typical dataset, most observations differ from the mean. When we create a model, we are trying to generate an equation that will tell us by how much each observation will differ from the mean. Obviously, the vast majority of models are not perfect. They can only predict some of the variation from the mean but not all of it. We attribute the rest of the difference between the actual value and the mean to random error. We would like random error to explain the as little as possible of the variation. This is why the r squared score is an important metric.

In the next cell, compute the r squared score of the model. Do this by first computing the predicted values and assign them to `y_pred`.

In [128]:
# Import the necessary function:
from sklearn.metrics import r2_score

In [152]:
y_pred = amodel.predict(x_test)
y_pred

array([28.50568128, 32.66283713, 28.01094861, 24.81835391, 26.0176343 ,
       13.46170998, 11.0173895 , 23.02760428, 26.51227578, 17.60860295,
       30.81136095, 33.51407346,  9.57658426,  4.75968123, 26.9851505 ,
        8.82421919, 10.179323  , 29.92199484, 19.45259967, 25.92627335,
       15.28246962, 25.28921747, 33.33041055, 26.014869  , 22.98047411,
       25.89579235, 29.06304179,  7.57411791, 20.93592265, 29.59097301,
       33.6058105 , 27.72275378, 25.42178947, 19.60343041, 14.59862706,
       28.8361855 , 31.42845048, 26.42173022, 26.58531608, 27.87257368,
        9.94926733, 15.57008999, 19.67294831, 20.96550785, 32.36172998,
        8.9995509 , 30.2705719 , 25.87813601, 30.32115038, 24.5870519 ,
       22.0300187 , 11.80614504, 34.02054695, 24.12674842, 31.84536935,
       24.37433034, 25.75863425, 25.56690459, 29.8924157 , 33.93048991,
       13.55513006, 12.47937965, 23.81843311, 18.92375167, 28.91326832,
       25.14461745,  7.92920952, 14.86693771, 15.88515846, 21.84

In [160]:
r2_score(y_test, y_pred)

0.7323215311891841

#### Our next step is to evaluate the model using the test data. We would like to ensure that our model is not overfitting the data. This means that our model will not be able to generalize well outside of the training data.

In the cell below, use the model to generate the predicted values for the training data and assign them to `y_test_pred`. Compute the r squared score for the test data by comparing the oberserved `y_test` data and the predicted `y_test_pred`.

In [156]:
y_test_pred = amodel.predict(X_train)
y_test_pred

array([21.70069251, 30.26596784, 28.00875495, 24.95083469, 10.35727972,
       22.20031314, 28.91167403, 23.3109372 , 22.13638382, 29.54938417,
       11.4218929 , 15.19393102, 24.25813565, 22.17718319, 30.89552807,
       22.18797099, 11.21272401, 23.56300386, 25.42210266, 29.02650777,
       33.03035179, 16.28140748, 31.29266689, 29.73684053, 31.66168962,
       20.57824807,  9.35132222, 22.12743851, 20.99055487, 20.90731915,
       33.8585271 , 23.14601163, 32.86857304, 26.60368959, 20.49620904,
       26.49234723, 23.77373189, 22.85239302, 17.62201634, 20.53817719,
       32.16169678, 34.76676287, 31.10397182, 16.47754234, 29.8506483 ,
       24.87405804, 28.60504666, 25.74623726, 20.91516137, 20.06648369,
       22.52503303, 32.04600871, 30.50222001, 17.3049366 , 11.34158588,
       26.66702911, 25.08745285, 11.91593102, 12.27677457, 21.46299555,
       29.53564618, 21.46451002, 22.87624764, 30.291046  , 24.54269758,
       28.1524504 , 14.17849263, 26.97500751, 23.71999995, 30.20

In [163]:
# Your code here:
r2_score(y_test_pred, Y_train)

0.7887044188917637

# Challenge 4 - Improve the Model Fit

While the most common way to improve the fit of a model is by using regularization, there are other simpler ways to improve model fit. The first is to create a simpler model. The second is to increase the train sample size.

Let us start with the easier option and increase our train sample size to 90% of the data. Create a new test train split and name the new predictors and response variables `X_train09`, `X_test09`, `y_train09`, `y_test09`.

In [167]:
# Your code here:
X_train09, x_test09, Y_train09, y_test09 = train_test_split(data_x,data_y, test_size=0.1, random_state=None)

Initialize a new model. Name this model `auto_model09`. Fit the model to the new sample data.

In [171]:
# Your code here:
auto_model09 = LinearRegression()

Compute the predicted values and r squared score for our new model and new sample data.

In [173]:
# Your code here:
modell = auto_model09.fit(X_train09,Y_train09)
modell

LinearRegression()

In [181]:
y_pred09 = modell.predict(x_test09)
y_pred09

array([22.07331158, 12.41465739, 18.09677017, 31.20329171, 31.20523708,
       20.0492612 , 34.57518642, 28.4657717 , 23.83361677, 25.57777854,
       16.05126873, 11.6011792 , 34.67488975, 26.17141484, 16.61901516,
       31.08083179, 27.65604626, 26.85498594, 11.95599604, 21.25716321,
       26.49599155, 21.39372864, 34.54838683, 29.44252052,  9.89006243,
       17.87581855, 15.76739405, 21.4191325 ,  9.90011018, 21.35073617,
       32.03505674, 31.95521132, 16.95228228,  7.86006619, 33.47371923,
       11.72368337, 25.76513055, 16.86419554, 11.56960162, 34.05692454])

Compute the r squared score for the smaller test set. Is there an improvement in the test r squared?

In [184]:
# Your code here:
r2_score(y_test09, y_pred09)

0.8343214652369614

In [186]:
from sklearn.metrics import mean_squared_error

mean_squared_error(y_test09, y_pred09)

12.108350627501059

# Bonus Challenge 2 - Backward Elimination 

The main way to produce a simpler linear regression model is to reduce the number of variables used in the model. In scikit-learn, we can do this by using recursive feature elimination. You can read more about RFE [here](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFE.html).

In the next cell, we will import RFE

Follow the documentation and initialize an RFE model using the `auto_model` linear regression model. Set `n_features_to_select=3`

In [200]:
# Your code here:



Fit the model and print the ranking

In [201]:
# Your code here:



Feature importance is ranked from most important (1) to least important (4). Generate a model with the three most important features. The features correspond to variable names. For example, feature 1 is `cylinders` and feature 2 is `displacement`.

Perform a test-train split on this reduced column data and call the split data `X_train_reduced`, `X_test_reduced`, `y_test_reduced`, `y_train_reduced`. Use an 80% split.

In [202]:
# Your code here:



Generate a new model called `auto_model_reduced` and fit this model. Then proceed to compute the r squared score for the model. Did this cause an improvement in the r squared score?

In [203]:
# Your code here: 

